### ISSUE TITLE
pass ip through LB

### ISSUE THREAD

**Issue by yonatonreid** [darkhelmet/balance#12]
is it possible to obtain the IP requesting the LB with the api balance server endpoints? currently when i make a request to the LB the ip address being used in the api servers is that of the load balancer. Im using the tcp balancer. Maybe this is something that should be done with curl?

**Comment by darkhelmet** [comment]
I think if you're using TCP balancing that's just going to be what you get. I don't know for sure though.

**Comment by yonatonreid** [comment]
is it possible to modify your code to add writing an ip address in the header that i can use in the tcp api code? maybe use https://en.wikipedia.org/wiki/X-Forwarded-For

**Comment by darkhelmet** [comment]
X-Forwarded-For is for HTTP so it doesn't apply to TCP load balancing.

**Comment by yonatonreid** [comment]
k thanks!
